spring:
  application:
    name: admin-quartz
  cloud:
    zookeeper:
      connect-string: 10.60.105.38:8352
  datasource:
    url : jdbc:mysql://10.60.105.37:8920/bccs3_admin?characterEncoding=utf-8&zeroDateTimeBehavior=convertToNull
    username : db_cluster
    password : bccs3_maria
    driverClassName : com.mysql.jdbc.Driver
server:
  port: 8080